export default {
    "bai-1": "Bài 1: 대인관계 (Quan hệ nhân giao)",
    "bai-2": "Bài 2: 성격 (Tính cách)",
    "bai-3": "Bài 3: Dịch vụ phúc lợi địa phương",
    "bai-4": "Bài 4: 직업 (Nghề nghiệp)",
    "bai-5": "Bài 5: 여행 (Du lịch)",
    "bai-6": "Bài 6: 건강 (Sức khỏe)",
    "bai-7": "Bài 7: 교육 (Giáo dục)",
    "bai-8": "Bài 8: 문화생활 (Văn hóa và đời sống)",
    "bai-9": "Bài 9: 환경 (Môi trường)",
    "bai-10": "Bài 10: 경제생활 (Kinh tế và đời sống)",
    "bai-11": "Bài 11: 사회문제 (Vấn đề xã hội)",
    "bai-12": "Bài 12: 정치 (Chính trị)",
    "bai-13": "Bài 13: 역사 (Lịch sử)",
    "bai-14": "Bài 14: 과학기술 (Khoa học và công nghệ)",
    "bai-15": "Bài 15: 예술 (Nghệ thuật)",
    "bai-16": "Bài 16: 종교 (Tôn giáo)",
    "bai-17": "Bài 17: 미디어 (Truyền thông)",
    "bai-18": "Bài 18: 스포츠 (Thể thao)"
};
