export default {
    "bai-1": "Bài 1: 대인관계 (Quan hệ nhân giao)",
    "bai-2": "Bài 2: 성격 (Tính cách)",
    "bai-3": "Bài 3: 지역 복지 서비스 (Dịch vụ phúc lợi địa phương)",
    "bai-4": "Bài 4: 교환과 환불 (TRAO ĐỔI VÀ HOÀN TRẢ)",
    "bai-5": "Bài 5: 소비와 절약 (Tiêu dùng và tiết kiệm)",
    "bai-6": "Bài 6: 주거 환경 (Môi trường sống)",
    "bai-7": "Bài 7: 문화생활 (Đời sống văn hóa)",
    "bai-8": "Bài 8: 음식과 요리 (Thực phẩm và Nấu ăn)",
    "bai-9": "Bài 9: 고장과 수리 (Hỏng hóc và Sửa chữa)",
    "bai-10": "Bài 10: 경제생활 (Kinh tế và đời sống)",
    "bai-11": "Bài 11: 사회문제 (Vấn đề xã hội)",
    "bai-12": "Bài 12: 정치 (Chính trị)",
    "bai-13": "Bài 13: 역사 (Lịch sử)",
    "bai-14": "Bài 14: 과학기술 (Khoa học và công nghệ)",
    "bai-15": "Bài 15: 예술 (Nghệ thuật)",
    "bai-16": "Bài 16: 종교 (Tôn giáo)",
    "bai-17": "Bài 17: 미디어 (Truyền thông)",
    "bai-18": "Bài 18: 스포츠 (Thể thao)"
};
