export default {
    "lesson_0": "Bài 0: Khóa học FastAPI Python",
    "lesson_1": "Bài 1: Giới thiệu FastAPI và môi trường làm việc",
    "lesson_2": "Bài 2: Tạo route cơ bản trong FastAPI",
    "lesson_3": "Bài 3: Sử dụng Path Parameters và Query Parameters",
    "lesson_4": "Bài 4: Request Body và kiểu dữ liệu cơ bản",
    "lesson_5": "Bài 5: Sử dụng các method HTTP khác (PUT, DELETE)",
    "lesson_6": "Bài 6: Quản lý dữ liệu tạm (Storage tạm thời)",
    "lesson_7": "Bài 7: Validation nâng cao với Pydantic",
    "lesson_8": "Bài 8: Response Model và Custom Response",
    "lesson_9": "Bài 9: Xử lý lỗi và Exception trong FastAPI",
    "lesson_10": "Bài 10: Dependency Injection cơ bản",
    "lesson_11": "Bài 11: Sử dụng Header và Cookie",
    "lesson_12": "Bài 12: Tạo và sử dụng Middleware",
    "lesson_13": "Bài 13: CORS trong FastAPI",
    "lesson_14": "Bài 14: Sử dụng Background Tasks",
    "lesson_15": "Bài 15: Upload và download file đơn giản",
    "lesson_16": "Bài 16: Template rendering với Jinja2",
    "lesson_17": "Bài 17: Xử lý Form data",
    "lesson_18": "Bài 18: Làm việc với Query Parameters nâng cao",
    "lesson_19": "Bài 19: Pagination (Phân trang đơn giản)",
    "lesson_20": "Bài 20: Sử dụng Enum trong FastAPI",
    "lesson_21": "Bài 21: Tạo API với đường dẫn động phức tạp",
    "lesson_22": "Bài 22: Sử dụng OAuth2 Password (Cơ bản)",
    "lesson_23": "Bài 23: Xác thực user với token (Basic)",
    "lesson_24": "Bài 24: Giới thiệu SQLAlchemy và kết nối DB SQLite",
    "lesson_25": "Bài 25: CRUD hoàn chỉnh với DB",
    "lesson_26": "Bài 26: Migrations đơn giản với Alembic (cơ bản)",
    "lesson_27": "Bài 27: Cấu hình logging trong FastAPI",
    "lesson_28": "Bài 28: Sử dụng WebSocket cơ bản",
    "lesson_29": "Bài 29: Pagination với DB và SQLAlchemy",
    "lesson_30": "Bài 30: Upload file lưu vào thư mục server",
    "lesson_31": "Bài 31: Quản lý CORS nâng cao",
    "lesson_32": "Bài 32: Đóng gói và triển khai ứng dụng FastAPI",
    "lesson_33": "Bài 33: Tổng kết và bài tập thực hành toàn khóa"
};