export default {
    "lesson_0": "Bài 0: Khóa học Gin Framework",
    "lesson_1": "Bài 1: Giới thiệu về Gin Framework",
    "lesson_2": "Bài 2: Cấu trúc dự án và Routing cơ bản",
    "lesson_3": "Bài 3: Handlers và Context",
    "lesson_4": "Bài 4: Request Binding và Validation",
    "lesson_5": "Bài 5: Template Rendering",
    "lesson_6": "Bài 6: Middleware cơ bản",
    "lesson_7": "Bài 7: Error Handling",
    "lesson_8": "Bài 8: File Upload và Download",
    "lesson_9": "Bài 9: Database Integration với GORM",
    "lesson_10": "Bài 10: Advanced GORM Operations",
    "lesson_11": "Bài 11: Authentication JWT",
    "lesson_12": "Bài 12: Authorization và Role-Based Access",
    "lesson_13": "Bài 13: API Versioning",
    "lesson_14": "Bài 14: Rate Limiting và Security",
    "lesson_15": "Bài 15: Caching Strategies",
    "lesson_16": "Bài 16: Background Jobs và Message Queues",
    "lesson_17": "Bài 17: Testing Gin Applications",
    "lesson_18": "Bài 18: API Documentation với Swagger",
    "lesson_19": "Bài 19: Monitoring và Logging",
    "lesson_20": "Bài 20: WebSocket và Real-time Features",
    "lesson_21": "Bài 21: Microservices với Gin",
    "lesson_22": "Bài 22: Deployment và Production Best Practices"
};
