export default {
    "bai-0": "Bài 0: Giới thiệu khóa học",
    "bai-1": "Bài 1: Giới thiệu và JavaScript Basics",
    "bai-2": "Bài 2: React Fundamentals và Frontend Frameworks",
    "bai-3": "Bài 3: SPA vs SSR và giới thiệu Next.js",
    "bai-4": "Bài 4: Khởi tạo dự án với create-next-app",
    "bai-5": "Bài 5: Next.js App Router - Routing Basics",
    "bai-6": "Bài 6: Layouts, Templates và Navigation",
    "bai-7": "Bài 7: Advanced Routing Patterns",
    "bai-8": "Bài 8: Rendering Strategies",
    "bai-9": "Bài 9: Data Fetching Fundamentals",
    "bai-10": "Bài 10: Advanced Data Fetching và Caching",
    "bai-11": "Bài 11: Server Actions và Forms",
    "bai-12": "Bài 12: Styling và CSS Solutions",
    "bai-13": "Bài 13: Assets Optimization",
    "bai-14": "Bài 14: Metadata, SEO và Third-party Integration",
    "bai-15": "Bài 15: API Routes và Backend Integration",
    "bai-16": "Bài 16: Testing và Quality Assurance",
    "bai-17": "Bài 17: Performance Optimization và Monitoring",
    "bai-18": "Bài 18: Production Deployment"
};
