export default {
    "bai-0": "Bài 0: Giới thiệu khóa học",
    "bai-1": "BÀI 1: GIỚI THIỆU VỀ RUST VÀ CÀI ĐẶT MÔI TRƯỜNG",
    "bai-2": "BÀI 2: CÚ PHÁP CƠ BẢN VÀ BIẾN",
    "bai-3": "BÀI 3: KIỂU DỮ LIỆU CƠ BẢN",
    "bai-4": "BÀI 4: CONTROL FLOW VÀ FUNCTIONS",
    "bai-5": "BÀI 5: STRINGS VÀ COLLECTIONS CƠ BẢN",
    "bai-6": "BÀI 6: STRUCTS VÀ ENUMS",
    "bai-7": "BÀI 7: PATTERN MATCHING VÀ DESTRUCTURING",
    "bai-8": "BÀI 8: OWNERSHIP SYSTEM - CORE CONCEPTS",
    "bai-9": "BÀI 9: BORROWING, REFERENCES VÀ SLICES",
    "bai-10": "BÀI 10: ERROR HANDLING",
    "bai-11": "BÀI 11: MODULES VÀ CRATES",
    "bai-12": "BÀI 12: TRAITS - SHARED BEHAVIOR",
    "bai-13": "BÀI 13: GENERICS VÀ TYPE-LEVEL PROGRAMMING",
    "bai-14": "BÀI 14: LIFETIMES VÀ BORROW CHECKER",
    "bai-15": "BÀI 15: ADVANCED COLLECTIONS VÀ CONCURRENCY BASICS",
    "bai-16": "BÀI 16: ASYNC PROGRAMMING",
    "bai-17": "BÀI 17: MACROS VÀ TESTING",
    "bai-18": "BÀI 18: WEB DEVELOPMENT VÀ ECOSYSTEM"
};
